# Generated by Django 5.2.4 on 2025-07-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_api', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
